
name: Release
on:
  schedule:
    - cron: "5 */12 * * *"
  push:
    branches:
      - "master"


jobs:
  Brave:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Download Brave
      run: |
        set -u
        curl https://api.github.com/repos/brave/brave-browser/releases/latest > /tmp/brave.json
        cat /tmp/brave.json| jq '.assets[].browser_download_url' | grep linux | grep -v symbols
        wget "$(cat /tmp/brave.json| jq -r '.assets[].browser_download_url' | grep linux | grep -v symbols)"
        VERSION="$(cat /tmp/brave.json| jq -r .tag_name)"
        echo "BRAVE_VERSION=$VERSION" >> $GITHUB_ENV
        if ls *nightly*.zip 1> /dev/null 2>&1; then
          # this is a nightly release
          # mark as pre release
          BRAVE_PRERELEASE=true
          BRAVE_TYPE=nightly
          APPDIR=AppDir-Nightly
          ICON=brave-browser-nightly
        elif ls *dev*.zip 1> /dev/null 2>&1; then
          # this is a dev release
          # mark as pre release
          BRAVE_PRERELEASE=true
          BRAVE_TYPE=dev
          APPDIR=AppDir-Dev
          ICON=brave-browser-dev
        elif ls *beta*.zip 1> /dev/null 2>&1; then
          # this is a beta release
          # mark as pre release
          BRAVE_PRERELEASE=true
          BRAVE_TYPE=beta
          APPDIR=AppDir-Beta
          ICON=brave-browser
        else
          BRAVE_PRERELEASE=false
          BRAVE_TYPE=stable
          APPDIR=AppDir
          ICON=brave-browser
        fi
        echo "BRAVE_TYPE=$BRAVE_TYPE" >> $GITHUB_ENV
        echo "BRAVE_PRERELEASE=$BRAVE_PRERELEASE" >> $GITHUB_ENV
        cp *.zip $APPDIR/.
        cd $APPDIR
        unzip *.zip && rm -r *.zip
        ln -sr product*logo*.png "$ICON.png"
        cd ..

        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x *.AppImage
        echo "AppDir: $APPDIR"
        ls -al
        ls -al "$APPDIR"
        ./appimagetool-x86_64.AppImage --comp gzip "$APPDIR" -n -u 'gh-releases-zsync|srevinsaju|Brave.AppImage|$BRAVE_TYPE|Brave*.AppImage.zsync'
        mkdir dist
        mv Brave*.AppImage* dist/.
       

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: brave-continuous.AppImage
        path: 'dist'

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: Brave AppImage ${{ env.BRAVE_VERSION }} Build
        automatic_release_tag: ${{ env.BRAVE_VERSION }}
        prerelease: ${{ env.BRAVE_PRERELEASE }}
        files: |
          dist/
        repo_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Release Continuous
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: Brave AppImage Continuous ${{ env.BRAVE_TYPE }} Build
        automatic_release_tag: ${{ env.BRAVE_TYPE }}
        prerelease: true
        files: |
          dist/
        repo_token: ${{ secrets.GITHUB_TOKEN }}

